ci:
  autoupdate_schedule: quarterly
  skip: [pip-compile]
default_language_version:
    python: python3.10
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.26
    hooks:
      - id: pip-compile
        name: pip-compile requirements_base.in
        args: [requirements_base.in, -o, requirements_base.txt]
        files: ^requirements_base\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements.in
        args: [requirements.in, -o, requirements.txt]
        files: ^requirements(_base)?\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements_dev.in
        args: [requirements_dev.in, -o, requirements_dev.txt]
        files: ^requirements(_base|_dev)?\.(in|txt)$
  - repo: local
    hooks:
      - id: sha256sum
        name: sha256sum
        language: unsupported
        entry: sh -c 'sha256sum requirements.txt > requirements.txt.sha256'
        files: ^requirements\.txt$
        pass_filenames: false
      - id: scrapy-checkall
        name: scrapy-checkall
        language: python
        entry: scrapy checkall --loglevel=WARNING
        files: ^kingfisher_scrapy/spiders
        additional_dependencies: [form2request, ijson, jsonpointer, pathvalidate, pydantic, orjson, rarfile, "scrapy>=2.15"]
