#!/usr/bin/env python
import argparse
import os
import logging.config
import json
import ocdskingfisher.cli.util
import ocdskingfisher.config


def main():

    config = ocdskingfisher.config.Config()
    config.load_user_config()

    logging_config_file_full_paths = [
        os.path.expanduser('~/.config/ocdskingfisher/logging.json'),
        os.path.expanduser('~/.config/ocdsdata/logging.json'),
    ]
    for logging_config_file_full_path in logging_config_file_full_paths:
        if os.path.isfile(logging_config_file_full_path):
            with open(logging_config_file_full_path) as f:
                logging.config.dictConfig(json.load(f))
            break

    parser = argparse.ArgumentParser()
    parser.add_argument("--verbose", help="increase output verbosity",
                        action="store_true")

    subparsers = parser.add_subparsers(dest='subcommand')

    commands = ocdskingfisher.cli.util.gather_cli_commands_instances(config=config)

    for command in commands.values():
        command.configure_subparser(subparsers.add_parser(command.command))

    args = parser.parse_args()

    if args.subcommand and args.subcommand in commands.keys():
        commands[args.subcommand].run_command(args)
    else:
        print("Please select a subcommand (try --help)")


if __name__ == '__main__':
    main()
