name: Lint
on: [push, pull_request]
jobs:
  lint:
    uses: open-contracting/.github/.github/workflows/lint.yml@main
    permissions:
      contents: write
    secrets:
      personal-access-token: ${{ secrets.PAT }}
    with:
      python-version: '3.10'
      # scrapyd is run as a command in production. scrapyd-client is run as a command for deployment.
      standard-maintenance-scripts-ignore: scrapyd,scrapyd-client
      before-lint: shasum -c requirements.txt.sha256
