name: CI (Non-Linux)
on: [push, pull_request]
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: pip
          cache-dependency-path: '**/requirements*.txt'
      - name: Install postgresql (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install postgresql
      - run: pip install -r requirements_dev.txt
      - env:
          CI_SKIP: true
        # https://github.com/pytest-dev/pytest-twisted/issues/183
        run: pytest -W error -W ignore::DeprecationWarning:pytest_twisted -rs --cov kingfisher_scrapy
      - run: python test_delayed_request_middleware.py
