import os
from importlib import import_module
from itertools import groupby
from textwrap import dedent

from scrapy.commands import ScrapyCommand
from scrapy.utils.misc import walk_modules
from scrapy.utils.spider import iter_spider_classes


class UpdateDocs(ScrapyCommand):
    def short_desc(self):
        return 'Update docs/spiders.rst'

    def run(self, args, opts):
        basedir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

        def _keyfunc(module):
            return module.__name__.rsplit('.', 1)[-1].split('_', 1)[0]

        with open(os.path.join(basedir, 'docs', 'spiders.rst'), 'w') as f:
            f.write(dedent("""\
            Spiders
            =======

            ..  Do not edit this file. Instead, run: `scrapy updatedocs`
            """))

            for key, group in groupby(walk_modules('kingfisher_scrapy.spiders'), _keyfunc):
                if key in ('spiders', 'test'):
                    continue

                f.write('\n{}\n{}\n'.format(key.capitalize(), '-' * len(key)))

                for module in group:
                    for cls in iter_spider_classes(module):
                        f.write('\n.. autoclass:: {}.{}\n   :no-members:\n'.format(module.__name__, cls.__name__))
